Add `python3-setuptools` package for Debian
cisagov/ansible-role-pip pull request #61
Opened 2024-03-20 19:00 UTC by jsf9k

## 🗣 Description ##

This pull request adds the package `python3-setuptools` for Debian-based OSs.  This change should be reverted when that becomes possible.

## 💭 Motivation and context ##

This is being done because the package should be getting installed as a dependency, but that is not happening on Kali Linux right now.  (Kali Linux is based on Debian Testing.)  See #60 for more details.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

2024-03-20 20:21 UTC, dav3r approved these changes
LGTM with one minor note. 👍

2024-03-20 20:21 UTC, dav3r commented on molecule/default/tests/test_default.py
> +        "python3-setuptools",
Alphabetize:
```suggestion
        "python3-dev",
        "python3-distutils",
        "python3-pip",
        "python3-setuptools",
```

2024-03-20 20:35 UTC, dv4harr10 approved these changes

2024-03-20 20:55 UTC, mcdonnnj requested changes
Thanks for the fix 👍 However, please update the README to mirror other changes in this PR around platforms no longer supported:
https://github.com/cisagov/ansible-role-pip/blob/7155d3c43bfcd2c808253036628bc860b5c0f382/README.md?plain=1#L18

2024-03-20 23:47 UTC, jsf9k commented
Please see commit 1fca4a0.

2024-03-21 02:20 UTC, jsf9k commented
> Thanks for the fix 👍However, please update the README to mirror other changes in this PR around platforms no longer supported:
> 
> https://github.com/cisagov/ansible-role-pip/blob/7155d3c43bfcd2c808253036628bc860b5c0f382/README.md?plain=1#L18

Please see commit 1fca4a0.  I will amend [cisagov/ansible-role-python](https://github.com/cisagov/ansible-role-python) similarly tomorrow.

2024-03-21 12:37 UTC, mcdonnnj approved these changes

2024-03-21 12:37 UTC, merged